version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      BQxwkRjO+FNFaZiXUoGxJOsZZ0pNcFSyEv2KAo26Ziv9G1wRRZ2MZ6x30l9pBCAx+JdD7UeSHned3RFv5hrpIk1/C1EWFTole6wRFZdZ1cqOkQbB9l7Ph12Ju2eR1sNZAoa7AJBDEfIV7utx96n1jpokU5FmYgmTS05PwnvZubhwUvZHUhAn/zaRKOgapup0DdSdoKSQ01nDDlHYWa1rz7rs+pwWXKZXtXViCRb8wBlMJyTnk/tJNWBjCkMvdr2MZaMo7Y25SeCIlxsDLwt23BQylm31B6VYI3xtPzpKQyAQgwZX7bGWTraUBzF9yM/dkFwvN87VmUs2xrQA5pPMIYQzsRJy6bcdD+htLHmS7E+pffwxcMvElxeuwf5I/q+7bcNAOCq88I+XHgBKlJKwhhJLEf2VN+XUfxCCLYU5sKIacmKm+Au6j+gri+Ac5BQmnH48Lex00qap6wk3Y2rONEfN32FtQ0JoU7q+15SnZuhn6h+QalwcL2WESPGm5hub5Ovpah25K7mZLjk9ZYozVmiu+Qs+qXzPEwFHJn/FF2bczFfKfi5AY23hqe38C+sw5fM+y+USDMGncf7ySp2p6ibWVhitK/6g/C2g01kQF7EyGaeod6EWGD/B4M51noEhh2dS8BzaLJAAsZV8sEEvbYN2TRHTGgXipctRm54xJdM=
