version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      xhCZWmZtqsuX0oDMFcp/13bp024sJSuFqQQ6y7du6PgXTcB8RBSzWkkHLKa6FVfbiCMLprfuxI0JEuUzBZiK+PcZoS/gg5HswtobCy2ysPWgaGirgDZJE56UW5ob5Vsrj2+BO0c05mm1871hfwrngFtn/ksP1NpFs2NUyBJItBcNriE7ArjtgWAE3Bx6Q2o2Gout+yL3ob/v0HtAgK+x5wG3ciqdNCERZlOQvyqA9NzE9I+kp6S164ZIqL589DACvkDOvBa847fuXkqx0SvESZ2qoji9baka+nQZVEfi5+WX7Wq4gGT3lsMQsGxxSIyFXowySB8AlDPW2b7orvL/PNSvV0WpUr/SriTpijlyGK4xdk8m29Ivyz0aNBiKY6feVPYF6I6toRx04QB7B2F7mkIdWO/WVmP/z/pXzdqbbOhLTVFzP5mwranYPyQi4TPsSZ6wf4VMA6EN+vcumOxuBDONYpDT/Ass2AgBPqqr7GoXm9e+lnNP6SoGz7R/SFjW6yK7TZ7nxxna3BGBvdhtjil/EBZZGtjJseYye2IQ4WRWJqNUqfdpOVWsAIdmzhe1BhUH9SdsnfLa9ZBxEu3JCK/6km1N0oGjeug/iTfcSdPt91aNGY5GmNW9EFq6ZNpE/WGQOtyDBlwab7eDyw0swLThgdbW9jQt/XKK/SXFJbU=
