version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      USytIV5wN6OVOQTqrSvawFpXsiCteSzTWIqLKLwt1Iis9ydIICGWjBnnNFayZ1+BfbVpckkbNDMwA8y9klWV4ZVSsBxZjbPLvVoTg6gqcWR23/gBZTDHyDJb0DAFclkDavbvVzXeP6puWUQpvQ+1jXBL6VGBYNyW1tS0yctTUERYpkAdvgK82O7B9lqacZE/mEzHNygok1BYBP2+mmEq/MXK0SumUA2vMtSbKVj1zMw2YvjO+2EBlbkiPJQEIFxMNjWlsk6dYrU81G88juIlG4/o1eqW2l+/CoG9sTj8xeNU5iDL/hAAEUv3bo8CuY3CEzUnENufAgK8skUJqRN0nC2LxEbkcFYZzsynotpAUR9XXAh4OMd3lShGMbsGk6OVIrolAVWwpU5ZdMICer59Ph4T6ak/PHCMk6OJ//yaelXaJ6L2I+isSYinLMCo7YN2J8pGTBMbeQsU4+tACZC0jojid5JHbuKk3q4vY0k4Zv6+CnQ850mP063GAfHYOZkcO0/FFXv2z+hYrWRVG2sJXC0a6mT4IVR/ABHlf7mzcWI1+KuTFzb1gRogXnNkQX6qKFOobyqAMewfsPB1w0mn3O0jVt2NeUHoI7hm9iWME/7RUCLx8zcGN9v1ZJ4i5RDPh7yRtaP4UQOglCmRAg/mATioqJl18xp2/buYBPqK9XI=
